FROM <%= config.BaseImage %>

# Get updates and install rubygems
RUN apt-get -y update
RUN apt-get -y install rubygems-integration
RUN apt-get -y install ruby-dev
RUN echo "gem: --no-ri --no-rdoc" > ~/.gemrc
RUN apt-get -y install build-essential

RUN gem install puppet librarian-puppet

RUN apt-get -y -q install wget git-core

ADD Puppetfile /
ADD init.pp /

<% if !config.PrePuppetCommands.nil? && config.PrePuppetCommands.length > 0 %>
#Run commands before executing puppet install
<% for @execs in config.PrePuppetCommands %>
RUN <%= @execs %>
<% end %>
<% end %>

#Install puppet dependencies
RUN librarian-puppet install

#Run puppet apply
RUN puppet apply --modulepath=/modules ./init.pp

<% if !config.PostPuppetCommands.nil? && config.PostPuppetCommands.length > 0 %>
#Run commands after executing puppet install
<% for @execs in config.PostPuppetCommands %>
RUN <%= @execs %>
<% end %>
<% end %>
